### ISSUE TITLE
vue路由中使用高级异步组件

### ISSUE THREAD

**Issue by mino01x** [jkchao/vue-demo#2]
```js
const AsyncComp = () => ({  
// The component to load. Should be a Promise
  component: import('./MyComp.vue'),  
// A component to use while the async component is loading
  loading: LoadingComp,  
// A component to use if the load fails
  error: ErrorComp,  
// Delay before showing the loading component. Default: 200ms. 
  delay: 200,  
// The error component will be displayed if a timeout is  
// provided and exceeded. Default: Infinity.
  timeout: 3000})
```
> Note that when used as a route component in vue-router, these properties will be ignored because async components are resolved upfront before the route navigation happens. You also need to use vue-router 2.4.0+ if you wish to use the above syntax for route components.

在路由组件会忽视上面的属性，但是后面又说2.4.0以上的vue-router支持。

请问，自己测试了一下，发现2.4.0+没有什么作用。在您vue-demo里面demo5页面也一样。就是要实现切换路由有一个loading的效果，谢谢~

**Comment by jkchao** [comment]
@Huahua-Chen 
你好
- 路由上的异步加载可以参考下这个 https://github.com/genu/vue-router-bug/blob/master/src/router/index.js
- 切换路由带 loading 效果，并不适合用异步组件功能来做，因为路由上的异步组件只能触发一次，以后就会被缓存了。你可以在路由里面的组件使用异步加载，带 loading 效果。
